config/routes.rb
Rails.application.routes.draw do
  root 'payees#index'

  resources :payees
  resources :payout_batches, only: %i(index show new create) do
    member do
      post 'post'
      get 'fetch'
    end
  end

end

app/models/payout_batch.rb
# == Schema Information
#
# Table name: payout_batches
#
#  id              :integer          not null, primary key
#  status          :string
#  sender_batch_id :string
#  email_subject   :string
#  amount          :float            default(0.0), not null
#  currency_id     :integer
#  fees            :float            default(0.0), not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  paypal_id       :string
#

class PayoutBatch < ActiveRecord::Base
  before_validation :set_unsent_status, on: :create
  before_validation :set_sender_batch_it, on: :create

  has_many :payout_items, dependent: :destroy
  has_many :payees, through: :payout_items
  belongs_to :currency

  validates :status, presence: true
  validates :sender_batch_id, presence: true,
    uniqueness: { case_sensitive: false }

  validates :amount, presence: true,
    numericality: { greater_than_or_equal_to: 0 }

  validates :fees, presence: true,
    numericality: { greater_than_or_equal_to: 0 }

  validates :currency, presence: true

  def fetch
    begin
      pp_payout_batch = PayPal::SDK::REST::Payout.get(self.paypal_id)
      update_from_paypal(pp_payout_batch)
    rescue PayPal::SDK::Core::Exceptions::ResourceNotFound
      self.errors.add(:base, 'PayoutBatch not found')
      false
    end
  end

  def post
    if self.status == 'UNSENT'
      paypal_payout = PayPal::SDK::REST::Payout.new(format_for_paypal)
      pp_payout_batch = paypal_payout.create

      if pp_payout_batch.error
        self.errors.add(:base, pp_payout_batch.error['details'].first['issue'])
        false
      else
        update_from_paypal(pp_payout_batch)
      end
    end
  end

  def format_for_paypal
    { sender_batch_header: {
        sender_batch_id: self.sender_batch_id,
        email_subject: self.email_subject },
      items: self.payout_items.map(&:format_for_paypal) }
  end

  def update_from_paypal(pp_payout_batch)
    self.paypal_id = pp_payout_batch.batch_header.payout_batch_id
    self.status = pp_payout_batch.batch_header.batch_status
    self.amount = pp_payout_batch.batch_header.amount.value.to_f
    self.fees = pp_payout_batch.batch_header.fees.value.to_f
    save!

    update_items_from_paypal(pp_payout_batch)
  end

  def sent?
    self.status != 'UNSENT'
  end

  def unsent?
    self.status == 'UNSENT'
  end

  private

  def set_unsent_status
    self.status = 'UNSENT' if self.status.blank?
  end

  def set_sender_batch_it
    self.sender_batch_id = SecureRandom.hex(8) if self.sender_batch_id.blank?
  end

  def update_items_from_paypal(pp_payout_batch)
    pp_payout_batch.items.each do |item_details|
      payout_item = self.payout_items.
        find_by(sender_item_id: item_details.payout_item.sender_item_id)

      payout_item.update_from_paypal(item_details)
    end
  end
end

app/controllers/payout_batches_controller.rb
class PayoutBatchesController < ApplicationController
  before_action :set_payout_batch, only: %i(show post fetch)

  def index
    @payout_batches = PayoutBatch.all
  end

  def show
  end

  def new
    @payout_batch = PayoutBatch.new
  end

  def create
    batch_params = payout_batch_params
    payee_ids = batch_params.delete(:payee_ids)
    @payout_batch = PayoutBatch.new(batch_params)

    Payee.where(id: payee_ids).each do |payee|
      @payout_batch.payout_items.build(amount: payee.balance,
                                       currency_id: @payout_batch.currency_id,
                                       payee: payee)
    end

    if @payout_batch.save
      redirect_to @payout_batch,
        notice: 'Payout batch was successfully created.'
    else
      render :new
    end
  end

  def fetch
    if @payout_batch.fetch
      redirect_to @payout_batch,
        notice: 'PayoutBatch refreshed successfully!'
    else
      flash[:alert] = @payout_batch.errors.full_messages.join(', ')
      render :show
    end
  end

  def post
    if @payout_batch.post
      redirect_to @payout_batch,
        notice: 'PayoutBatch sent to Paypal successfully!'
    else
      flash[:alert] = @payout_batch.errors.full_messages.join(', ')
      render :show
    end
  end

  private

  def set_payout_batch
    @payout_batch = PayoutBatch.find(params[:id])
  end

  def payout_batch_params
    params.require(:payout_batch).permit(:email_subject, :currency_id,
                                         payee_ids: [])
  end
end

app/views/payout_batches/_form.html.erb
<%= form_for(@payout_batch) do |f| %>
  <% if @payout_batch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payout_batch.errors.count, "error") %> prohibited this payout batch from being saved:</h2>

      <ul>
      <% @payout_batch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email_subject %><br>
    <%= f.text_field :email_subject %>
  </div>
  <div class="field">
    <%= f.label :currency %><br>
    <%= f.collection_select(:currency_id, Currency.all, :id, :code) %>
  </div>
  <div class="field">
    <%= f.label :payees %><br>
    <%= f.collection_check_boxes(:payee_ids, Payee.all, :id, :email_currency) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payout_batches/index.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<h1>Listing Payout batches</h1>

<table>
  <thead>
    <tr>
      <th>Paypal ID</th>
      <th>Status</th>
      <th>Amount</th>
      <th>Currency</th>
      <th>Sender batch ID</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @payout_batches.each do |batch| %>
      <tr>
        <td><%= batch.paypal_id %></td>
        <td><%= batch.status %></td>
        <td><%= batch.amount %></td>
        <td><%= batch.currency %></td>
        <td><%= batch.sender_batch_id %></td>
        <td><%= link_to 'Show', batch %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New batch', new_payout_batch_path %>

app/views/payout_batches/new.html.erb
<h1>New Payout batch</h1>

<%= render 'form' %>

<%= link_to 'Back', payout_batches_path %>

app/views/payout_batches/show.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<p>
  <strong>Paypal ID:</strong>
  <%= @payout_batch.paypal_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @payout_batch.status %>
</p>

<p>
  <strong>Sender batch ID:</strong>
  <%= @payout_batch.sender_batch_id %>
</p>

<p>
  <strong>Email subject:</strong>
  <%= @payout_batch.email_subject %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @payout_batch.amount %>
</p>

<p>
  <strong>Fees:</strong>
  <%= @payout_batch.fees %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @payout_batch.currency %>
</p>

<% if @payout_batch.payout_items.empty? %>
  <p>
    <strong>Items:</strong>
    No items
  </p>

<% else %>
  <p>
    <strong>Items:</strong>
  </p>

  <table>
    <thead>
      <tr>
        <th>Paypal ID</th>
        <th>Transaction ID</th>
        <th>Sender item ID</th>
        <th>Transaction status</th>
        <th>Amount</th>
        <th>Fees</th>
        <th>Currency</th>
        <th>Time processed</th>
        <th>Payee email</th>
        <th>Error</th>
      </tr>
    </thead>

    <tbody>
      <% @payout_batch.payout_items.each do |item| %>
        <tr>
          <td><%= item.paypal_id %></td>
          <td><%= item.transaction_id %></td>
          <td><%= item.sender_item_id %></td>
          <td><%= item.transaction_status %></td>
          <td><%= item.amount %></td>
          <td><%= item.fees %></td>
          <td><%= item.currency %></td>
          <td><%= item.time_processed %></td>
          <td><%= item.payee.email %></td>
          <td><%= item.error %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
<% end %>


<%= link_to('Post', post_payout_batch_path(@payout_batch), method: :post) if @payout_batch.unsent? %>
<%= link_to('Refresh', fetch_payout_batch_path(@payout_batch)) if @payout_batch.sent? %>
<%= link_to 'Back', payout_batches_path %>