config/routes.rb
Rails.application.routes.draw do
  root 'payees#index'

  resources :payees
  resources :payout_batches, only: %i(index show new create) do
    member do
      post 'post'
      get 'fetch'
    end
  end

end

app/models/payee.rb
# == Schema Information
#
# Table name: payees
#
#  id          :integer          not null, primary key
#  email       :string
#  balance     :float
#  currency_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Payee < ActiveRecord::Base
  has_many :payout_items
  has_many :payout_batches, through: :payout_items

  belongs_to :currency

  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :balance, presence: true,
    numericality: { greater_than_or_equal_to: 0 }

  validates :currency, presence: true

  def email_currency
    "#{self.email}_#{self.currency}"
  end

end

app/controllers/payees_controller.rb
class PayeesController < ApplicationController
  before_action :set_payee, only: [:show, :edit, :update, :destroy, :pay,
                                   :confirm]

  # GET /payees
  # GET /payees.json
  def index
    @payees = Payee.all
  end

  # GET /payees/1
  # GET /payees/1.json
  def show
  end

  # GET /payees/new
  def new
    @payee = Payee.new
    @payee.balance = 20
  end

  # GET /payees/1/edit
  def edit
  end

  # POST /payees
  # POST /payees.json
  def create
    @payee = Payee.new(payee_params)

    if @payee.save
      redirect_to @payee, notice: 'Payee was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /payees/1
  # PATCH/PUT /payees/1.json
  def update
    if @payee.update(payee_params)
      redirect_to @payee, notice: 'Payee was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /payees/1
  # DELETE /payees/1.json
  def destroy
    @payee.destroy
    redirect_to payees_url, notice: 'Payee was successfully destroyed.'
  end

  def pay
    payout_response = @payee.make_payout

    if payout_response.ok?
      redirect_to @payee, notice: 'Payout was successfully processed.'
    else
      redirect_to @payee, alert: "Payout failed: #{payout_response.body}"
    end
  end

  def confirm
    if params[:tag] == @payee.return_tag
      @payee.signed = true
      @payee.save!

      redirect_to @payee, notice: 'Payoneer sign up successful'
    else
      redirect_to @payee, alert: 'Payoneer sign up fail'
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_payee
    @payee = Payee.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def payee_params
    params.require(:payee).permit(:email, :balance, :currency_id)
  end
end

app/views/payees/_form.html.erb
<%= form_for(@payee) do |f| %>
  <% if @payee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payee.errors.count, "error") %> prohibited this payee from being saved:</h2>

      <ul>
      <% @payee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :balance %><br>
    <%= f.text_field :balance %>
  </div>
  <div class="field">
    <%= f.label :currency %><br>
    <%= f.collection_select(:currency_id, Currency.all, :id, :code) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payees/edit.html.erb
<h1>Editing Payee</h1>

<%= render 'form' %>

<%= link_to 'Show', @payee %> |
<%= link_to 'Back', payees_path %>

app/views/payees/index.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<h1>Listing Payees</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Balance</th>
      <th>Currency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payees.each do |payee| %>
      <tr>
        <td><%= payee.email %></td>
        <td><%= payee.balance %></td>
        <td><%= payee.currency.code %></td>
        <td><%= link_to 'Show', payee %></td>
        <td><%= link_to 'Edit', edit_payee_path(payee) %></td>
        <td><%= link_to 'Destroy', payee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payee', new_payee_path %>

app/views/payees/new.html.erb
<h1>New Payee</h1>

<%= render 'form' %>

<%= link_to 'Back', payees_path %>

app/views/payees/show.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<p>
  <strong>Email:</strong>
  <%= @payee.email %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @payee.balance %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @payee.currency.code %>
</p>

<%= link_to 'Edit', edit_payee_path(@payee) %> |
<%= link_to 'Back', payees_path %>